export const getData = (state) => state.loadIngredients;
export const getIngredients = (state) => state.burgerConstructor;
export const createOrder = (state) => state.createOrder;
export const getOrder = (state) => state.getOrder;
export const getDisplayedIngredient = (state) => state.ingredientWindow.displayedIngredient;
export const getTab = (state) => state.tabInfo.tab;
export const getAuth = (state) => state.auth;
export const getOrdersAll = (state) => state.ordersAll;
export const getOrdersUser = (state) => state.ordersUser;